### ISSUE TITLE
I would like to have a license added.

### ISSUE THREAD

**Issue by rapan931** [gosagawa/atcoder#1]
Goで競プロ参加しようと考えています。

本リポジトリのフォーマットや作りを参考にさせていただきたいのですが、ライセンスがなかったため、可能であればライセンスの追加をお願いいたします。

**Comment by gosagawa** [comment]
申し訳ありません、こちらを直接見てはおらず気付くのが遅れました。
好きに使っていただいて問題なく、MIT Licenseを設定しておきましたのでお願いします。

**Comment by rapan931** [comment]
ありがとうございます！！！！

**Comment by rapan931** [comment]
closeしますね。対応ありがとうございました。
